services:
  gcs:
    image: fsouza/fake-gcs-server:latest
    container_name: fake-gcs
    ports:
      - "4443:4443"
    command:
      - "-scheme"
      - "http"
      - "-port"
      - "4443"
      - "-public-host"
      - "localhost:4443"
      - "-external-url"
      - "http://localhost:4443"
      - "-backend"
      - "filesystem"
      - "-filesystem-root"
      - "/storage"
    volumes:
      - ./gcs-data:/data
      - ./gcs-storage:/storage
