export const auditEventCatalog = {
    "agent.create": { category: "agent" },
    "agent.delete": { category: "agent" },
    "agent.key_read": { category: "agent" },
    "agent.update": { category: "agent" },
    "api_key.create": { category: "api_key" },
    "api_key.delete": { category: "api_key" },
    "auth.email_verification_complete": { category: "auth" },
    "auth.login": { category: "auth" },
    "auth.logout": { category: "auth" },
    "auth.password_reset_complete": { category: "auth" },
    "auth.password_reset_request": { category: "auth" },
    "auth.two_factor_disable": { category: "auth" },
    "auth.two_factor_enable": { category: "auth" },
    "backup.delete": { category: "backup" },
    "backup.download": { category: "backup" },
    "backup.finish": { category: "backup" },
    "backup.import": { category: "backup" },
    "backup.request": { category: "backup" },
    "database.create": { category: "database" },
    "database.update": { category: "database" },
    "notification_channel.create": { category: "notification_channel" },
    "notification_channel.delete": { category: "notification_channel" },
    "notification_channel.update": { category: "notification_channel" },
    "organization.create": { category: "organization" },
    "organization.delete": { category: "organization" },
    "organization.update": { category: "organization" },
    "organization_member.add": { category: "organization_member" },
    "organization_member.remove": { category: "organization_member" },
    "organization_member.role_update": { category: "organization_member" },
    "project.create": { category: "project" },
    "project.delete": { category: "project" },
    "project.update": { category: "project" },
    "restore.delete": { category: "restore" },
    "restore.finish": { category: "restore" },
    "restore.request": { category: "restore" },
    "restore.rerun": { category: "restore" },
    "settings.encryption_key_download": { category: "settings" },
    "storage_channel.create": { category: "storage_channel" },
    "storage_channel.delete": { category: "storage_channel" },
    "storage_channel.update": { category: "storage_channel" },
    "user.create": { category: "user" },
    "user.delete": { category: "user" },
    "user.role_update": { category: "user" },
    "user.update": { category: "user" },
} as const;

export const auditEventTypes = Object.keys(auditEventCatalog).sort((a, b) => a.localeCompare(b));
export const auditCategories = [...new Set(Object.values(auditEventCatalog).map((entry) => entry.category))]
    .sort((a, b) => a.localeCompare(b));
export const auditOutcomeOptions = ["success", "failure", "denied"] as const;
