name: PR Checker

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  dry-run:
    name: Dry run
    runs-on: ${{ matrix.platform == 'linux/amd64' && 'ubuntu-latest' || 'ubuntu-24.04-arm' }}
    strategy:
      fail-fast: false
      matrix:
        platform: [linux/amd64, linux/arm64]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/dockerfile/Dockerfile
          platforms: ${{ matrix.platform }}
          push: false
          tags: portabase/portabase:pr-${{ github.event.number }}
          cache-from: type=gha,scope=build-${{ matrix.platform }}
          cache-to: type=gha,mode=max,scope=build-${{ matrix.platform }}

      - name: Prepare Artifact Data
        id: prep
        run: |
          SAFE_PLATFORM=${{ matrix.platform == 'linux/amd64' && 'linux-amd64' || 'linux-arm64' }}
          echo "safe_platform=$SAFE_PLATFORM" >> $GITHUB_OUTPUT
          echo "portabase/portabase:pr-${{ github.event.number }}" > image.txt

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: image-${{ steps.prep.outputs.safe_platform }}
          path: image.txt
          retention-days: 1
